<?php
// include composer autoload
require 'vendor/autoload.php';

use Imagine\Gd\Font;
use Imagine\Image\Box;
use Imagine\Image\Palette\RGB;
use Imagine\Image\Point;

$imagine = new Imagine\Imagick\Imagine();


$image0 = $imagine->open('0.png');
$image1 =  $imagine->open('1.png');
$image2 =  $imagine->open('2.png');
$image3 =  $imagine->open('3.png');
$image4 =  $imagine->open('4.png');
$image5 =  $imagine->open('5.png');
$image6 =  $imagine->open('6.png');
$image7 =  $imagine->open('7.png');
$image8 =  $imagine->open('8.png');
$image9 =  $imagine->open('9.png');
$image10 =  $imagine->open('10.png');

$image0->layers()
    ->add($image1)
    ->add($image2)
    ->add($image3)
    ->add($image4)
    ->add($image5)
    ->add($image6)
    ->add($image7)
    ->add($image8)
    ->add($image9)
    ->add($image10)
    ->add($image1)
    ->add($image2)
    ->add($image3)
    ->add($image4)
    ->add($image5)
    ->add($image6)
    ->add($image7)
    ->add($image8)
    ->add($image9)
    ->add($image10)
    ->add($image1)
    ->add($image2)
    ->add($image3)
    ->add($image4)
    ->add($image5)
    ->add($image6)
    ->add($image7)
    ->add($image8)
    ->add($image9)
    ->add($image10)
    ->add($image1)
    ->add($image2)
    ->add($image3)
    ->add($image4)
    ->add($image5)
    ->add($image6)
    ->add($image7)
    ->add($image8)
    ->add($image9)
    ->add($image10)
    ->add($image1)
    ->add($image2)
    ->add($image3)
    ->add($image4)
    ->add($image5)
    ->add($image6)
    ->add($image7)
    ->add($image8)
    ->add($image9)
    ->add($image10)
    ->add($image1)
    ->add($image2)
    ->add($image3)
    ->add($image4)
    ->add($image5)
    ->add($image6)
    ->add($image7)
    ->add($image8)
    ->add($image9)
    ->add($image10)
    ->add($image1)
    ->add($image2)
    ->add($image3)
    ->add($image4)
    ->add($image5)
    ->add($image6)
    ->add($image7)
    ->add($image8)
    ->add($image9)
    ->add($image10)
    ->add($image1)
    ->add($image2)
    ->add($image3)
    ->add($image4)
    ->add($image5)
    ->add($image6)
    ->add($image7)
    ->add($image8)
    ->add($image9)
    ->add($image10)
    ->add($image1)
    ->add($image2)
    ->add($image3)
    ->add($image4)
    ->add($image5)
    ->add($image6)
    ->add($image7)
    ->add($image8)
    ->add($image9)
    ->add($image10)
    ->add($image1)
    ->add($image2)
    ->add($image3)
    ->add($image4)
    ->add($image5)
    ->add($image6)
    ->add($image7)
    ->add($image8)
    ->add($image9)
    ->add($image10)
    ->add($image1)
    ->add($image2)
    ->add($image3)
    ->add($image4)
    ->add($image5)
    ->add($image6)
    ->add($image7)
    ->add($image8)
    ->add($image9)
    ->add($image10)
    ->add($image1)
    ->add($image2)
    ->add($image3)
    ->add($image4)
    ->add($image5)
    ->add($image6)
    ->add($image7)
    ->add($image8)
    ->add($image9)
    ->add($image10)
    ->add($image1)
    ->add($image2)
    ->add($image3)
    ->add($image4)
    ->add($image5)
    ->add($image6)
    ->add($image7)
    ->add($image8)
    ->add($image9)
    ->add($image10)
    ->add($image1)
    ->add($image2)
    ->add($image3)
    ->add($image4)
    ->add($image5)
    ->add($image6)
    ->add($image7)
    ->add($image8)
    ->add($image9)
    ->add($image10)
    ->add($image1)
    ->add($image2)
    ->add($image3)
    ->add($image4)
    ->add($image5)
    ->add($image6)
    ->add($image7)
    ->add($image8)
    ->add($image9)
    ->add($image10)
    ->add($image1)
    ->add($image2)
    ->add($image3)
    ->add($image4)
    ->add($image5)
    ->add($image6)
    ->add($image7)
    ->add($image8)
    ->add($image9)
    ->add($image10)
    ->add($image1)
    ->add($image2)
    ->add($image3)
    ->add($image4)
    ->add($image5)
    ->add($image6)
    ->add($image7)
    ->add($image8)
    ->add($image9)
    ->add($image10)
    ->add($image1)
    ->add($image2)
    ->add($image3)
    ->add($image4)
    ->add($image5)
    ->add($image6)
    ->add($image7)
    ->add($image8)
    ->add($image9)
    ->add($image10)
    ->add($image1)
    ->add($image2)
    ->add($image3)
    ->add($image4)
    ->add($image5)
    ->add($image6)
    ->add($image7)
    ->add($image8)
    ->add($image9)
    ->add($image10)
    ->add($image1)
    ->add($image2)
    ->add($image3)
    ->add($image4)
    ->add($image5)
    ->add($image6)
    ->add($image7)
    ->add($image8)
    ->add($image9)
    ->add($image10)
    ->add($image1)
    ->add($image2)
    ->add($image3)
    ->add($image4)
    ->add($image5)
    ->add($image6)
    ->add($image7)
    ->add($image8)
    ->add($image9)
    ->add($image10)
    ->add($image1)
    ->add($image2)
    ->add($image3)
    ->add($image4)
    ->add($image5)
    ->add($image6)
    ->add($image7)
    ->add($image8)
    ->add($image9)
    ->add($image10);

$image0->show('gif', array(
    'animated' => true,
));
